// src/lib/settings/registry.ts
// Central registry of settings categories used by the admin sidebar and settings pages.

import { Building2, Cog, Users, ClipboardList, ShieldCheck, CreditCard, LineChart, MessageSquare, PlugZap, ServerCog, Upload, Clock } from 'lucide-react'
import type { SettingsCategory } from './types'
import { PERMISSIONS } from '@/lib/permissions'

// Keep tabs empty here — individual category modules will register their own tabs or the registry can be extended at runtime.
// Added `group` and `order` metadata to support grouped navigation and deterministic ordering.
export const SETTINGS_REGISTRY: SettingsCategory[] = [
  {
    key: 'organization',
    label: 'Organization Settings',
    route: '/admin/settings/company',
    icon: Building2,
    tabs: [],
    // permission optional — can be used by UI to hide entries
    permission: PERMISSIONS.ORG_SETTINGS_VIEW,
    group: 'platform',
    order: 10,
  },
  {
    key: 'serviceManagement',
    label: 'Service Management',
    route: '/admin/settings/services',
    icon: ClipboardList,
    tabs: [],
    group: 'platform',
    order: 20,
  },
  {
    key: 'booking',
    label: 'Booking Configuration',
    route: '/admin/settings/booking',
    icon: Cog,
    tabs: [],
    permission: PERMISSIONS.BOOKING_SETTINGS_VIEW,
    group: 'business',
    order: 30,
  },
  {
    key: 'clientManagement',
    label: 'Client Management',
    route: '/admin/settings/clients',
    icon: Users,
    tabs: [],
    permission: PERMISSIONS.CLIENT_SETTINGS_VIEW,
    group: 'business',
    order: 40,
  },
  {
    key: 'taskWorkflow',
    label: 'Task & Workflow',
    route: '/admin/settings/tasks',
    icon: ClipboardList,
    tabs: [],
    permission: PERMISSIONS.TASK_WORKFLOW_SETTINGS_VIEW,
    group: 'operations',
    order: 50,
  },
  {
    key: 'teamManagement',
    label: 'Team Management',
    route: '/admin/settings/team',
    icon: Users,
    tabs: [],
    permission: PERMISSIONS.TEAM_SETTINGS_VIEW,
    group: 'operations',
    order: 60,
  },
  {
    key: 'financial',
    label: 'Financial Settings',
    route: '/admin/settings/financial',
    icon: CreditCard,
    tabs: [],
    permission: PERMISSIONS.FINANCIAL_SETTINGS_VIEW,
    group: 'financial',
    order: 70,
  },
  {
    key: 'analyticsReporting',
    label: 'Analytics & Reporting',
    route: '/admin/settings/analytics',
    icon: LineChart,
    tabs: [],
    permission: PERMISSIONS.ANALYTICS_REPORTING_SETTINGS_VIEW,
    group: 'financial',
    order: 80,
  },
  {
    key: 'communication',
    label: 'Communication',
    route: '/admin/settings/communication',
    icon: MessageSquare,
    tabs: [],
    permission: PERMISSIONS.COMMUNICATION_SETTINGS_VIEW,
    group: 'platform',
    order: 90,
  },
  {
    key: 'securityCompliance',
    label: 'Security & Compliance',
    route: '/admin/settings/security',
    icon: ShieldCheck,
    tabs: [],
    permission: PERMISSIONS.SECURITY_COMPLIANCE_SETTINGS_VIEW,
    group: 'security',
    order: 100,
  },
  {
    key: 'integrationHub',
    label: 'Integration Hub',
    route: '/admin/settings/integrations',
    icon: PlugZap,
    tabs: [],
    permission: PERMISSIONS.INTEGRATION_HUB_VIEW,
    group: 'integrations',
    order: 110,
  },
  {
    key: 'systemAdministration',
    label: 'System Administration',
    route: '/admin/settings/system',
    icon: ServerCog,
    tabs: [],
    permission: PERMISSIONS.SYSTEM_ADMIN_SETTINGS_VIEW,
    group: 'platform',
    order: 120,
  },
  // Explicit system items that were previously top-level routes
  {
    key: 'users',
    label: 'Users & Permissions',
    route: '/admin/settings/users',
    icon: Users,
    tabs: [],
    permission: PERMISSIONS.USERS_VIEW,
    group: 'security',
    order: 130,
  },
  {
    key: 'uploads',
    label: 'Uploads',
    route: '/admin/settings/uploads',
    icon: Upload,
    tabs: [],
    permission: PERMISSIONS.SYSTEM_ADMIN_SETTINGS_VIEW,
    group: 'platform',
    order: 140,
  },
  {
    key: 'cron',
    label: 'Cron Telemetry',
    route: '/admin/settings/cron',
    icon: Clock,
    tabs: [],
    permission: PERMISSIONS.SYSTEM_ADMIN_SETTINGS_VIEW,
    group: 'platform',
    order: 150,
  }
]

export default SETTINGS_REGISTRY
