"use client"

import StandardPage from '@/components/dashboard/templates/StandardPage'
import PermissionGate from '@/components/PermissionGate'
import { PERMISSIONS } from '@/lib/permissions'
import { Download } from 'lucide-react'
// Explicit export endpoint references used by smoke tests:
// /api/admin/export?entity=users
// /api/admin/export?entity=bookings
// /api/admin/export?entity=services

// Admin Reports page: focuses on data export and summaries wiring.
// - Uses StandardPage template to align with QuickBooks-style layout
// - Provides explicit CSV export controls for Users, Bookings, and Services
// - Avoids server-side cron triggers (authorization required); keep client-only exports here
export default function AdminReportsPage() {
  const download = (entity: 'users' | 'bookings' | 'services') => {
    window.location.href = `/api/admin/export?entity=${entity}`
  }

  return (
    <StandardPage
      title="Reports"
      subtitle="Export data and review summarized analytics"
      secondaryActions={[
        { label: 'Export Users', icon: Download, onClick: () => download('users') },
        { label: 'Export Bookings', icon: Download, onClick: () => download('bookings') },
        { label: 'Export Services', icon: Download, onClick: () => download('services') },
      ]}
    >
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-2">Available Exports</h2>
          <p className="text-sm text-gray-600 mb-4">Download CSV snapshots for offline analysis and sharing.</p>
          <ul className="list-disc ml-5 space-y-1 text-sm text-gray-700">
            <li>Users: id, name, email, role, createdAt</li>
            <li>Bookings: id, client, service, status, scheduledAt, duration</li>
            <li>Services: id, name, category, price</li>
          </ul>
        </section>

        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-2">Report Generation</h2>
          <p className="text-sm text-gray-600">Automated monthly reports are generated by the scheduled job. For security, triggering cron tasks requires server authorization and is not exposed in the UI.</p>
        </section>
      </div>
    </StandardPage>
  )
}
