"use client"

import AnalyticsPage from '@/components/dashboard/templates/AnalyticsPage'
import PermissionGate from '@/components/PermissionGate'
import { PERMISSIONS } from '@/lib/permissions'
import { Download } from 'lucide-react'
import { downloadExport } from '@/lib/admin-export'
import type { KPIStatsProps } from '@/components/dashboard/analytics/ProfessionalKPIGrid'
// Explicit export endpoint references used by smoke tests:
// /api/admin/export?entity=users
// /api/admin/export?entity=bookings
// /api/admin/export?entity=services

// Admin Reports page: focuses on data export and summaries wiring.
// - Uses StandardPage template to align with QuickBooks-style layout
// - Provides explicit CSV export controls for Users, Bookings, and Services
// - Avoids server-side cron triggers (authorization required); keep client-only exports here
export default function AdminReportsPage() {
  const handleExport = (entity: 'users' | 'bookings' | 'services') => {
    downloadExport({ entity, format: 'csv' })
  }

  const placeholderStats: KPIStatsProps['stats'] = {
    revenue: { current: 0, target: 0, targetProgress: 0, trend: 0 },
    bookings: { total: 0, today: 0, pending: 0, conversion: 0 },
    clients: { active: 0, new: 0, retention: 0, satisfaction: 0 },
    tasks: { productivity: 0, completed: 0, overdue: 0, dueToday: 0 },
  }

  return (
    <PermissionGate permission={PERMISSIONS.ANALYTICS_VIEW} fallback={<AnalyticsPage title="Reports" subtitle="Export data and review summarized analytics" stats={placeholderStats}><div className="text-sm text-gray-600">You do not have permission to view this page.</div></AnalyticsPage>}>
      <AnalyticsPage
        title="Reports"
        subtitle="Export data and review summarized analytics"
        stats={placeholderStats}
        secondaryActions={[
          { label: 'Export Users', icon: Download, onClick: () => handleExport('users') },
          { label: 'Export Bookings', icon: Download, onClick: () => handleExport('bookings') },
          { label: 'Export Services', icon: Download, onClick: () => handleExport('services') },
        ]}
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <section className="bg-white rounded-lg border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Available Exports</h2>
            <p className="text-sm text-gray-600 mb-4">Download CSV snapshots for offline analysis and sharing.</p>
            <ul className="list-disc ml-5 space-y-1 text-sm text-gray-700">
              <li>Users: id, name, email, role, createdAt</li>
              <li>Bookings: id, client, service, status, scheduledAt, duration</li>
              <li>Services: id, name, category, price</li>
            </ul>
          </section>

          <section className="bg-white rounded-lg border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Report Generation</h2>
            <p className="text-sm text-gray-600">Automated monthly reports are generated by the scheduled job. For security, triggering cron tasks requires server authorization and is not exposed in the UI.</p>
          </section>
        </div>
      </AnalyticsPage>
    </PermissionGate>
  )
}
